// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBETwy2iG8OXB0FOPGci78ZeHYImugLzqY',
    appId: '1:544009711182:web:5902706886ecf31ac6dd1f',
    messagingSenderId: '544009711182',
    projectId: 'tetetete-9f956',
    authDomain: 'tetetete-9f956.firebaseapp.com',
    storageBucket: 'tetetete-9f956.appspot.com',
    measurementId: 'G-16BWXYL3FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhAgIpCx-Y8azdlv7G8Vo-HH_Ls-vbCrM',
    appId: '1:544009711182:android:a65924ecef6495cec6dd1f',
    messagingSenderId: '544009711182',
    projectId: 'tetetete-9f956',
    storageBucket: 'tetetete-9f956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAryCD6hpsVnkrN5_Oyr87J2oHuyPmK3oA',
    appId: '1:544009711182:ios:8f7b7365302d8b03c6dd1f',
    messagingSenderId: '544009711182',
    projectId: 'tetetete-9f956',
    storageBucket: 'tetetete-9f956.appspot.com',
    iosClientId: '544009711182-dj49asvpglldubv0a8hi61hj1b1s8nuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.banana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAryCD6hpsVnkrN5_Oyr87J2oHuyPmK3oA',
    appId: '1:544009711182:ios:1341afc161d0208cc6dd1f',
    messagingSenderId: '544009711182',
    projectId: 'tetetete-9f956',
    storageBucket: 'tetetete-9f956.appspot.com',
    iosClientId: '544009711182-a88fo8amduv8rhu539jn7mje4i8tl7a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.banana.RunnerTests',
  );
}
